### ISSUE TITLE
How do I get the app to log to firebase? 

### ISSUE THREAD

**Issue by rickrender** [andy9t7/a97-gpt-app#2]
I've set up the firebase and included the plist file to the app, along with the api for open ai. What do I need to setup in Firebase? I'm assuming it's the Firebase Database, but I'm not sure what values go where, could you please explain that bit a little? Still kind of new to Swift code but I was able to get it to compile and run on my iPhone, just doesn't log or show anything in the history tab because I'm assuming it has no idea where to store it on the Firebase side. 

Thanks for building out such a cool example project to play with, BTW, this is cool.

**Comment by andy9t7** [comment]
Hi Rick,

To log to firebase, I am using Cloud Firestore. I believe you will need to open/start the server on your firebase console for this to work. 

I'm glad you like it. It is very barebones and I may or may not work on it in the future :P

Thanks

<img width="1669" alt="Screenshot 2023-01-25 at 12 06 24 am" src="https://user-images.githubusercontent.com/40649135/214345540-a2d7b4b4-ebfc-4a90-83e0-6452c28e4a10.png">
